from panda3d.core import Vec3

# Window
WINDOW_TITLE = "Hella Driving"
GAME_WIDTH = 1440
GAME_HEIGHT = 810

VISION_WIDTH = 1440
VISION_HEIGHT = 810

WINDOW_WIDTH = GAME_WIDTH
WINDOW_HEIGHT = GAME_HEIGHT + VISION_HEIGHT

GAME_SCREEN_RATIO = GAME_WIDTH / GAME_HEIGHT

# Camera
CAMERA_OFFSET = Vec3(0, -12, 5)
CAMERA_LOOK_AT_HEIGHT = 1.2
CAMERA_SMOOTHNESS = 5.0

# Car
CAR_SCALE = 1.5
MAX_SPEED = 25.0
ACCELERATION = 12.0
BRAKE_FORCE = 20.0
DRAG = 8.0
MAX_TURN_RATE = 90.0
STEERING_SMOOTHNESS = 8.0

# World
GROUND_SIZE = 1000
TREE_SCALE = 3.0
TREE_SPACING = 28
TREE_AREA = 400

